### ISSUE TITLE
当日中の課題で、締め切り時間を超過した場合、残り時間の表示が1ヶ月ずれる

### ISSUE THREAD

**Issue by HALQME** [tomo0611/moodle-plus#1]
タイトル通り。

- 大学 : [omu.ac.jp]（https://lms.omu.ac.jp/)

- 環境
    - Apple M1 Max MacBook Pro / macOS 14.4.1（23E224）
    - Browser
        - Arc:バージョン1.39.1 (49071)
        - Chromium Engine: Version 124.0.6367.61

- 再現方法:不明（23:59〜0:00〆以外の課題を求められた場合？）

![名称未設定](https://github.com/tomo0611/moodle-plus/assets/68320771/e0b04f37-ef08-4f8c-8373-42784e979730)

**Comment by HALQME** [comment]
dateToString関数の
```typescript
function dateToString(date: Date, withDay: boolean = false): string {
    const day = date.getDate() - 1;
    //~~~
    let time = h + ":" + m + ":" + s;
    if (withDay && day !== 0) {
        time = day + "日 " + time;
    }
    return time;
}
```
のところで
`day`が`1..<31`だから`0-1`のところで核を撃つガンジーになっていて、
`day !== 0`だからdayがマイナスに突入した時に残り時間が30日と…になるのかもと思いました。

**Comment by tomo0611** [comment]
問題の発生理由自体は分かってるんですが、
そもそも課題一覧確認ページで過去の課題が出てきたことがないので、課題一覧が正しく取得できていない(キャッシュが使われてる等)を疑ってるんですよね～
処理自体を何とかするよりは取得回りを見直す方が本質的なのかなあと

**Comment by HALQME** [comment]
過ぎた課題が表示されるの自体が仕様範囲外なんですね…
リロードとかブラウザの再起動で消えたりしないからそんなもんやと､､､

**Comment by tomo0611** [comment]
どうやら締め切り後1時間まではupcomingのところに出てくるMoodle側の仕様っぽい
Mergeして閉じます。

ありがとう
