### ISSUE TITLE
滋賀大学対応追加要望

### ISSUE THREAD

**Issue by kazuyakunBBB** [tomo0611/moodle-plus#7]
滋賀大生です
とても素敵な拡張機能だと思っています。
https://sulms.shiga-u.ac.jp/
可能であればこのリンクでも有効化していただきたいです。

**Comment by tomo0611** [comment]
滋賀大のIDを持っていないのでこちらでは動作確認ができません。
デバッグモード等で動作確認お願いします。

**Comment by kazuyakunBBB** [comment]
既に当方で動作確認済みです。
Chrome等にも反映されていただきたいです

**Comment by tomo0611** [comment]
ありがとうございます。
Version 2.3として今日中に対応します。
よろしくお願いいたします。

**Comment by kazuyakunBBB** [comment]
よろしくお願いいたします🙇

**Comment by tomo0611** [comment]
遅くなりました。先ほどv2.3をアップロードしたので数日で対応されると思います。

**Comment by tomo0611** [comment]
ChromeとFirefoxで公開されました
動作するか確認お願いします。

https://chromewebstore.google.com/detail/moodle-plus/nncecmfhijadiddmmnajjaemlpnknplh

**Comment by kazuyakunBBB** [comment]
確認できました
しっかり動作しています
ご対応いただきありがとうございました
